project_name: zooom
builds:
  - env: [ CGO_ENABLED=0 ]
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
archives:
  - replacements:
      amd64: 64-bit
      386: 32-bit
      darwin: macOS
    wrap_in_directory: "{{ .ProjectName }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
      - src: examples/*.json
        dst: .
        strip_parent: true
